# Generated by Django 5.1 on 2024-08-26 08:35

import django.db.models.deletion
import django_choices_field.fields
import fruits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='色の名前', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='果物の品種名', max_length=20)),
                ('category', django_choices_field.fields.TextChoicesField(choices=[('citrus', '柑橘類'), ('berry', 'ベリー類')], choices_enum=fruits.models.FruitCategory, help_text='果物の分類', max_length=6)),
                ('color', models.ForeignKey(blank=True, help_text='この種類の果物の色', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='fruits.color')),
            ],
        ),
    ]
